// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf_cOniJ8OfpNOzT7NPXysNuU5GFMvkuo',
    appId: '1:470351622498:web:230cf86f1fd15939e37c3b',
    messagingSenderId: '470351622498',
    projectId: 'petguardian-bbc37',
    authDomain: 'petguardian-bbc37.firebaseapp.com',
    storageBucket: 'petguardian-bbc37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmYW-84-_houoD5zk5YCqriacTz9g-9HU',
    appId: '1:470351622498:android:1dd95325b9d2de48e37c3b',
    messagingSenderId: '470351622498',
    projectId: 'petguardian-bbc37',
    storageBucket: 'petguardian-bbc37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABSU4C1tXPci7mfQFDPDw8Nm6a0fBY0Tw',
    appId: '1:470351622498:ios:4cf884c47f6efdfce37c3b',
    messagingSenderId: '470351622498',
    projectId: 'petguardian-bbc37',
    storageBucket: 'petguardian-bbc37.appspot.com',
    iosClientId: '470351622498-du17rdaqejk492p6n34b9btue5sh4aj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.anasayfa',
  );
}
